http:
  middlewares:
    chain-no-auth:
      chain:
        middlewares:
          - middlewares-rate-limit
          #- middlewares-compress
 
    chain-basic-auth:
      chain:
        middlewares:
          - middlewares-rate-limit
          - middlewares-basic-auth
          #- middlewares-compress

