version: "3.9"

networks:
  default:
    driver: bridge
  zabbix_network:
    name: zabbix-net
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.90.0/24

services:
  zabbix-server:
    image: zabbix/zabbix-server-pgsql:alpine-6.4-latest
    container_name: zabbix-server
    platform: linux/arm64
    ports:
      - 10051:10051
    networks:
      - zabbix_network
    environment:
      - DB_SERVER_HOST=postgres-server
      - DB_SERVER_PORT=5432
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
    depends_on:
      - postgres-server
    restart: always

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:alpine-6.4-latest
    container_name: zabbix-web
    platform: linux/arm64
    ports:
      - 80:8080
    networks:
      - zabbix_network
    environment:
      - PHP_TZ=$TZ
      - ZBX_SERVER_HOST=zabbix-server
      - ZBX_SERVER_PORT=10051
      - DB_SERVER_HOST=postgres-server
      - DB_SERVER_PORT=5432
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      #- ENABLE_WEB_ACCESS_LOG=true
      #- ZBX_DB_ENCRYPTION=true
    depends_on:
      - postgres-server
      - zabbix-server
    restart: always

  postgres-server:
    image: arm64v8/postgres:16-alpine
    container_name: postgres-server
    ports:
      - 5432:5432
    networks:
      - zabbix_network
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
    volumes:
      - $DOCKERDIR/app/postgresql:/var/lib/postgresql/data
    restart: always

