version: "3.9"

networks:
  default:
    driver: bridge
  traefik_proxy:
    name: traefik_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.90.0/24

services:
  traefik:
    container_name: traefik
    image: traefik:2.10
    ## Always restart the container if it stops. If it's manually stopped, it's restarted only when Docker daemon restarts or the container itself is manually restarted.
    restart: always
    networks: 
      - traefik_proxy
    security_opt:
      - no-new-privileges:true
    command: # CLI arguments
      - --global.checkNewVersion=true
      - --global.sendAnonymousUsage=true
      ### API
      - --api=true
      ## Allow insecure connections during debugging
      - --api.insecure=true
      #- --serversTransport.insecureSkipVerify=true
      - --api.dashboard=true
      ### Entry Points
      - --entryPoints.http.address=:80
      - --entryPoints.https.address=:443
      - --entrypoints.https.forwardedHeaders.trustedIPs=$LOCAL_IPS
      - --entryPoints.traefik.address=:8080
      ### Logs
      - --log=true
      - --log.filePath=/logs/traefik.log
      - --log.level=INFO # (Default: error) DEBUG, INFO, WARN, ERROR, FATAL, PANIC
      - --accessLog=true
      - --accessLog.filePath=/logs/access.log
      - --accessLog.bufferingSize=100 # Configuring a buffer of 100 lines
      - --accessLog.filters.statusCodes=204-299,400-499,500-599
      ### Docker
      - --providers.docker=true
      - --providers.docker.endpoint=unix:///var/run/docker.sock # Use Docker Socket Proxy for improved security
      - --providers.docker.exposedByDefault=false
      - --providers.docker.defaultrule=Host(`{{ index .Labels "com.docker.compose.service" }}.$DOMAINNAME`)
      - --providers.docker.network=traefik_proxy
      - --providers.docker.swarmMode=false
      ### Rules
      - --providers.file.directory=/rules # Load dynamic configuration from one or more .toml or .yml files in a directory.
      - --providers.file.watch=true # Only works on top level files in the rules folder
      ### HTTPS
      - --entrypoints.https.http.tls.options=tls-opts@file
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - target: 8080  # Traefik dashboard
        published: 8080
        protocol: tcp
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro  # TODO: Use Docker Socket Proxy instead for improved security
      - $DOCKERDIR/app/traefik/rules:/rules
      - $DOCKERDIR/shared:/shared
      - $DOCKERDIR/logs:/logs
    environment:
      - TZ=$TZ
      - HTPASSWD_FILE=/shared/.htpasswd
    #labels:
      #- "traefik.enable=true"
      #- "traefik.http.routers.traefik-rtr.middlewares=chain-basic-auth@file"

  whoami:
    image: "traefik/whoami"
    container_name: "whoami"
    networks:
      - traefik_proxy
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      ### Routers
      - "traefik.http.routers.whoami-rtr.entrypoints=http,https"
      - "traefik.http.routers.whoami-rtr.rule=Host(`ns.$DOMAINNAME`)"
      ### Middlewares
      - "traefik.http.routers.whoami-rtr.middlewares=chain-no-auth@file"
      ### Services
      - "traefik.http.routers.whoami-rtr.service=whoami-svc"
      - "traefik.http.services.whoami-svc.loadbalancer.server.port=80"

