---
- hosts: kleo.local
#  become: yes

  tasks:
  - name: Create ~/docker directory
    file:
      path: "{{ docker_dir }}"
      state: directory
      mode: '0755'
  
  - name: Create ~/docker/shared directory
    file:
      path: "{{ shared_dir }}"
      state: directory
      mode: '0755'

  - name: Copy .htpasswd to the host
    copy:
      src: "../dns/.htpasswd"
      dest: "{{ shared_dir }}/.htpasswd"
      mode: '755'

  vars:
    docker_dir: "/home/{{ ansible_user_id }}/docker"
    shared_dir: "{{ docker_dir }}/shared"

