---
- hosts: all
  become: yes

  tasks:
  - name: Install packages
    apt:
      update_cache: yes
      name:
        - libffi-dev
        - libssl-dev
        - python3
        - python3-pip

  - name: Get docker convenience script for "{{ ansible_env.SUDO_USER }}"
    shell: curl -fsSL https://get.docker.com -o get-docker.sh
    args:
      creates: /home/{{ ansible_env.SUDO_USER }}/get-docker.sh

  - name: Install docker
    shell: sh /home/{{ ansible_env.SUDO_USER }}/get-docker.sh
    args:
      creates: /usr/bin/docker

  - name: Add "{{ ansible_env.SUDO_USER }}" user into docker group
    user:
      name: "{{ ansible_env.SUDO_USER }}"
      groups: docker
      append: yes

  - name: Install docker-compose
    pip:
      name: docker-compose
