---
- hosts: ns
  tasks:
  - name: Create ~/docker/... dirs
    file:
      path: "{{ item.name }}"
      state: directory
      mode: '0755'
    loop:
      - { name: "{{ docker_dir }}" }
      - { name: "{{ shared_dir }}" }
      - { name: "{{ app_dir }}" }
      - { name: "{{ logs_dir }}" }
      - { name: "{{ traefik_dir }}" }
      - { name: "{{ traefik_dir }}/rules" }
      - { name: "{{ unbound_dir }}" }

  - name: Move files to the host
    become: "{{ item.become }}"
    copy:
      src: "{{ item.from }}"
      dest: "{{ item.to }}"
      mode: "{{ item.mode }}"
    loop:
      - { from: "../ns/.env", to: "{{ docker_dir }}/.env", mode: "600", become: yes }
      - { from: "../ns/.htpasswd", to: "{{ shared_dir }}/.htpasswd", mode: "600", become: yes }
      - { from: "../docker/docker-compose-ns.yml", to: "{{ docker_dir }}/docker-compose.yml", mode: "644", become: no }
      - { from: "../ns/traefik-middlewares.yml", to: "{{ traefik_dir }}/rules/middlewares.yml", mode: "644", become: no }
      - { from: "../ns/traefik-middlewares-chains.yml", to: "{{ traefik_dir }}/rules/middlewares-chains.yml", mode: "644", become: no }
      - { from: "../ns/traefik-tls-opts.yml", to: "{{ traefik_dir }}/rules/tls-opts.yml", mode: "644", become: no }
      - { from: "../ns/unbound.conf", to: "{{ unbound_dir }}/unbound.conf", mode: "644", become: no }
      - { from: "../ns/a-records.conf", to: "{{ unbound_dir }}/a-records.conf", mode: "644", become: no }

  - name: Create empty log files
    file:
      path: "{{ logs_dir }}/{{ item.name }}"
      state: touch
      mode: '644'
      modification_time: preserve
      access_time: preserve
    loop:
      - { name: "traefik.log" }
      - { name: "access.log" }
      - { name: "error-pihole.log" }
      - { name: "unbound.log" }

  - name: Create and start docker services
    become: yes # Access to .env and other root-owned sensitive files
    docker_compose:
      project_src: "{{ docker_dir }}"

  - name: Update pihole-FTL config
    lineinfile:
      path: "{{ pihole_dir }}/pihole-FTL.conf"
      regexp: "^{{ item.key }}=.+$"
      line: "{{ item.key }}={{ item.value }}"
      state: present
    with_items:
      - "{{ ftl_config }}"
    register: ftl_config_status
 
  - set_fact: needs_pihole_restart=true
    when:
      item is changed
    with_items: 
      - "{{ ftl_config_status.results }}"

  vars:
    docker_dir: "/home/{{ ansible_user_id }}/docker"
    shared_dir: "{{ docker_dir }}/shared"
    app_dir: "{{ docker_dir }}/app"
    logs_dir: "{{ docker_dir }}/logs"
    traefik_dir: "{{ app_dir }}/traefik"
    pihole_dir: "{{ app_dir }}/pihole"  # Will be created by docker-compose
    unbound_dir: "{{ app_dir }}/unbound"
    ftl_config:
      # Anonymous mode: This disables basically everything except the live anonymous statistics
      # Set to 0 if you need full stats
      - key: "PRIVACYLEVEL"
        value: "3"
      # Allow iCloud Private Relay, e.g. mask.icloud.com and mask-h2.icloud.com 
      # Details: https://developer.apple.com/support/prepare-your-network-for-icloud-private-relay
      - key: "BLOCK_ICLOUD_PR"
        value: "false"

