---
- hosts: kleo.local
  tasks:
  - name: Create ~/docker/... dirs
    file:
      path: "{{ item.name }}"
      state: directory
      mode: '0755'
    loop:
      - { name: "{{ docker_dir }}" }
      - { name: "{{ shared_dir }}" }
      - { name: "{{ app_dir }}" }
      - { name: "{{ logs_dir }}" }
      - { name: "{{ traefik_dir }}" }
      - { name: "{{ traefik_dir }}/rules" }
      - { name: "{{ unbound_dir }}" }

  - name: Move files to the host
    become: "{{ item.become }}"
    copy:
      src: "{{ item.from }}"
      dest: "{{ item.to }}"
      mode: "{{ item.mode }}"
    loop:
      - { from: "../dns/.env", to: "{{ docker_dir }}/.env", mode: "600", become: yes }
      - { from: "../dns/.htpasswd", to: "{{ shared_dir }}/.htpasswd", mode: "600", become: yes }
      - { from: "../docker/docker-compose-dns.yml", to: "{{ docker_dir }}/docker-compose.yml", mode: "644", become: no }
      - { from: "../dns/traefik-middlewares.yml", to: "{{ traefik_dir }}/rules/middlewares.yml", mode: "644", become: no }
      - { from: "../dns/traefik-middlewares-chains.yml", to: "{{ traefik_dir }}/rules/middlewares-chains.yml", mode: "644", become: no }
      - { from: "../dns/traefik-tls-opts.yml", to: "{{ traefik_dir }}/rules/tls-opts.yml", mode: "644", become: no }
      - { from: "../dns/unbound.conf", to: "{{ unbound_dir }}/unbound.conf", mode: "644", become: no }
      - { from: "../dns/a-records.conf", to: "{{ unbound_dir }}/a-records.conf", mode: "644", become: no }

  - name: Create empty log files
    file:
      path: "{{ logs_dir }}/{{ item.name }}"
      state: touch
      mode: '644'
      modification_time: preserve
      access_time: preserve
    loop:
      - { name: "traefik.log" }
      - { name: "access.log" }
      - { name: "error-pihole.log" }
      - { name: "unbound.log" }

  - name: Create and start docker services
    become: yes # Access to .env and other root-owned sensitive files
    docker_compose:
      project_src: "{{ docker_dir }}"

  vars:
    docker_dir: "/home/{{ ansible_user_id }}/docker"
    shared_dir: "{{ docker_dir }}/shared"
    app_dir: "{{ docker_dir }}/app"
    logs_dir: "{{ docker_dir }}/logs"
    traefik_dir: "{{ app_dir }}/traefik"
    pihole_dir: "{{ app_dir }}/pihole"  # Will be created by docker-compose
    unbound_dir: "{{ app_dir }}/unbound"

