---
- hosts: all
  become: yes

  tasks:
  - name: Update list of available packages
    apt:
      update_cache: true
      cache_valid_time: 3600
  
  - name: Upgrade the system by installing/upgrading packages
    apt:
      upgrade: yes
  
  - name: Ensure Chrony (for time synchronization) is installed
    apt:
      name: chrony
      state: present

  - name: Ensure chrony is running
    service:
      name: chronyd
      state: started
      enabled: yes

  - name: Install git when necessary
    apt:
      name: git
      state: present

