---
- hosts: all 
  become: true
  
  # Full setup instruction:
  # https://github.com/UCTRONICS/SKU_RM0004/blob/main/README.md
  tasks:
    - name: Update boot configuration in config.txt
      lineinfile:
        path: /boot/config.txt
        regexp: '^{{ item.key }}=.*$'
        line: '{{ item.key }}={{ item.value }}'
        state: present
      with_items:
        - "{{ boot_config }}"
      register: config_update_status
    - set_fact: needs_reboot=true
      when:
        item is changed
      with_items: 
        - "{{ config_update_status.results }}"
    - name: Reboot to apply config changes
      reboot:
      when:
        - needs_reboot is defined
        - needs_reboot is true

  vars:
    lib_source: ~/SKU_RM0004
    boot_config:
      # Turn on i2c and set the speed
      - key: "dtparam=i2c_arm"
        value: "on"
      - key: "i2c_arm_baudrate"
        value: "400000"
      # Turn on the button to control the shutdown function 
      - key: "dtoverlay" 
        value: "gpio-shutdown"
      - key: "gpio_pin"
        value: "4"
      - key: "active_low"
        value: "1"
      - key: "gpio_pull"
        value: "up"


