---
- hosts: all 
  become: true
  
  # Full setup instruction:
  # https://github.com/UCTRONICS/SKU_RM0004/blob/main/README.md
  tasks:
    - name: Update boot configuration in config.txt
      lineinfile:
        path: /boot/config.txt
        regexp: "^{{ item.key }}=.*$"
        line: "{{ item.key }}={{ item.value }}"
        state: present
      with_items:
        - "{{ boot_config }}"
      register: config_update_status
    
    - set_fact: needs_reboot=true
      when:
        item is changed
      with_items: 
        - "{{ config_update_status.results }}"
   
    - name: Add i2c-dev to auto-start modules 
      lineinfile:
        dest: /etc/modules
        create: yes
        line: 'i2c-dev'
        state: present

    - name: Reboot to apply config changes
      reboot:
      when:
        - needs_reboot is defined
        - needs_reboot is true
    
    - name: Clone SKU_RM0004 library
      git:
        repo: https://github.com/UCTRONICS/SKU_RM0004.git 
        dest: "{{ lib_source }}"

    - name: Compile SKU_RM0004
      make:
        chdir: "{{ lib_source }}"

    - name: Copy display binary to /usr/bin
      copy:
        src: "{{ lib_source }}/display"
        dest: "/usr/bin/{{ lib_name }}"
        mode: '755'
        remote_src: true

    - name: Add "{{ lib_name }}" to the run-control script
      lineinfile:
        path: /etc/rc.local
        line: "{{ lib_name }}"
        insertbefore: "exit 0"
      register: runcontrol_update_status

    - name: Reboot to start SKU_RM0004 ./display
      reboot:
      when:
        runcontrol_update_status is changed

  vars:
    lib_source: ~/SKU_RM0004
    lib_name: start_display_manager
    boot_config:
      # Turn on i2c and set the speed
      - key: "dtparam=i2c_arm"
        value: "on"
      - key: "dtparam=2c_arm_baudrate"
        value: "400000"
      # Turn on the button to control the shutdown function 
      - key: "dtoverlay" 
        value: "gpio-shutdown"
      - key: "dtoverlay=gpio_pin"
        value: "4"
      - key: "dtoverlay=active_low"
        value: "1"
      - key: "dtoverlay=gpio_pull"
        value: "up"


