---
- hosts: all
  become: yes

  tasks:
  - name: Install Zabbix deb package from repository
    apt:
      deb: https://repo.zabbix.com/zabbix/6.4/raspbian/pool/main/z/zabbix-release/zabbix-release_6.4-1+debian11_all.deb 

  - name: Run apt update
    apt:
      update_cache: yes
  
  - name: Install Zabbix agent2 and plugins
    apt:
      name: zabbix-agent2,zabbix-agent2-plugin-*
      state: present

  - name: Start Zabbix agent2 process
    service:
      name: zabbix-agent2
      state: started

  - name: Make Zabbix agent2 process start at system boot
    service:
      name: zabbix-agent2
      enabled: yes

