---
- hosts: all
  become: yes

  tasks:
  - name: Install Zabbix deb package from repository
    become: true
    apt:
      deb: https://repo.zabbix.com/zabbix/6.4/raspbian/pool/main/z/zabbix-release/zabbix-release_6.4-1+debian11_all.deb 

  - name: Run apt update
    apt:
      update_cache: true
  
  - name: Install Zabbix agent2
    apt:
      name: zabbix-agent2
      state: present

  - name: Install Zabbix agent2 plugins
    apt:
      name: zabbix-agent2-plugin-*
      state: present

